#Loading in base datasets and setting wd
setwd("~/HOSPITAL BEDS")

library(tidyr)
library(dplyr)
library(readxl)
library(mltools)
library(data.table)
library(ggplot2)
library(foreach)
library(forecast)
library(deSolve)
library(tidyverse)
library(lubridate)
library(scales)
library(stringr)
library(sjmisc)
library(stringdist)
library(simmer)
library(simmer.plot)
library(expm)
library(tidyr)
library(timetk)
library(tsbox)
library(sweep)
library(tidyquant)
library(plotly)

admissions_daily <- read_excel("admissions_daily.xlsx")
admissions_daily_dch <- read_excel("admissions_daily_dch.xlsx")
midnight_beds <- read_excel("midnight_beds.xlsx")
midnight_beds_dch <- read_excel("midnight_beds_dch.xlsx")
los_ref <- read_excel("length of stay last 6 months.xlsx")
number_of_admissions_by_month <- read_excel("number of admissions by month.xlsx", 
                                            col_types = c("date", "text", "text", 
                                                          "text", "text", "text", "text", "numeric"))